[package]
name = "mdns_lite"
description = "An lightweight mDNS implementation."
version = "0.1.0"
edition = "2021"
authors = ["Alex Thomson <alexjthomson1882@gmail.com>"]

[lib]
name = "mdns_lite"
path = "src/lib.rs"

[dependencies]
log = { version = "0.4", default-features = false }
heapless = { version = "0.8", default-features = false }
thiserror = { version = "1.0", default-features = false }
mio = { version = "1.0", default-features = false, features = ["net", "os-poll"]}

[profile.dev]
opt-level = 1
debug = true
debug-assertions = true
overflow-checks = true
incremental = true

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
strip = true
lto = true
panic = "abort"

[[example]]
name = "broadcast"
path = "examples/broadcast.rs"